name: Docker Image Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag  manojkumar8008/javafile:${{github.sha}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: manojkumar8008/javafile:${{github.sha}}
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Required for CodeQL to upload results
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Build with Gradle/Maven
        run: mvn compile

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker image on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker pull manojkumar8008/javafile:${{github.sha}}
            sudo docker stop hello-world || true
            sudo docker rm hello-world || true
            sudo docker run -d --name hello-world -p 80:8080 manojkumar8008/javafile:${{github.sha}}
          
            